import 'normalize.css/normalize.css';
import '@/app/globals.scss';
import { poppins, permanent_marker } from '@/app/fonts'
import type { Metadata } from "next";

import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${permanent_marker.variable}`}>
      <body>
          <Header />
          {children}
        </body>
    </html>
  );
}
